class Translate:

    @staticmethod
    def get_translate():
        dic_translate = {
                'Passes Progressivos/Passes %': 'Passes Progressivos/Passes %',
                'Gol decisivo/gol %': 'Gol decisivo/gol %',
                'playerStats_assist': 'Assistência',
                'Passes Progressivos %': 'Passes Progressivos %',
                'playerStats_controlled_penalty_area_entry_success': 'Entrada na área com a bola controlada',
                'Passes Verticais/Passes %': 'Passes Verticais/Passes %',
                'playerStats_back_pass_to_gk_success': 'Passe curto pro goleiro',
                'playerStats_card_suffered': 'Cartão tomado',
                'playerStats_corner': 'Escanteio',
                'playerStats_corner_won_from_cross': 'Escanteio com cruzamento',
                'playerStats_dangerous_opponent_half_recovery': 'Recuperação de bola no campo adversário',
                'playerStats_direct_free_kick': 'Falta direta',
                'playerStats_ground_duel': 'Duelo no chão',
                'playerStats_legacy_won_duel': 'playerStats_legacy_won_duel',
                'playerStats_long_pass_or_cross': 'Passe longo ou cruzamento',
                'playerStats_lost_defensive_duel': 'Duelo defensivo perdido',
                'playerStats_offside': 'Impedimento',
                'playerStats_opportunity_creation_success': 'Oportunidade criada',
                'playerStats_pass_to_another_flank_success': 'Virada de jogo',
                'playerStats_pass_to_penalty_area_v2': 'Passe para a área do pênalti',
                'playerStats_pick_up_success': 'playerStats_opportunity_success',
                'playerStats_pressing_duel': 'Pressão',
                'playerStats_received_dangerous_pass': 'Passe perigoso recebido',
                'playerStats_right_throw_in': 'Lateral pela direita',
                'playerStats_shot_on_goal_success': 'Finalização no alvo',
                'playerStats_touch_in_penalty_area': 'Toques na área do pênalti',
                'playerStats_vertical_pass': 'Passe vertical',
                'playerStats_vertical_pass_success': 'Passe vertical',
                'playerStats_xg_save': 'xG save',
                'playerStats_action': 'Ações',
                'playerStats_any_goal': 'Gol',
                'playerStats_ball_delivery_to_danger_zone_success': 'Passe para zona perigosa',
                'playerStats_controlled_penalty_area_entry': 'Entrada na área com a bola controlada',
                'playerStats_corner_won_from_cross_success': 'Escanteio com cruzamento',
                'playerStats_covering_depth': 'Cobertura defensiva',
                'playerStats_cross_to_penalty_area': 'Cruzamento para a área do pênalti',
                'playerStats_dribble_against_with_take_on': 'Drible tomado com ultrapassagem',
                'playerStats_dribble_with_progress': 'Drible progressivo',
                'playerStats_dribble_won_v2': 'playerStats_dribble_won_v2',
                'playerStats_free_kick_shot': 'Finalização em falta direta',
                'playerStats_free_kick_shot_gained_success': 'playerStats_free_kick_shot_gained',
                'playerStats_heading': 'Cabeçada',
                'playerStats_inside_run_success': 'Corrida por dentro',
                'playerStats_key_pass_v2': 'Passe chave',
                'playerStats_loose_ball_duel_success': 'playerStats_loose_ball_duel_success',
                'playerStats_minus_success': 'playerStats_minus_success',
                'playerStats_offensive_duel_with_progress': 'Duelo ofensivo com progressão',
                'playerStats_opponent_half_recovery': 'Recuperação no campo adversário',
                'playerStats_pass_to_zone_fourteen': 'Passe para a zona 14',
                'playerStats_plus': 'playerStats_plus',
                'playerStats_real_won_duel': 'playerStats_legacy_won_duel',
                'playerStats_shot_from_box_success': 'Finalização de dentro da área',
                'playerStats_shot_from_cross': 'Finalização em cruzamentos',
                'playerStats_shot_on_goal_assist_success': 'Assistência para chute no alvo',
                'playerStats_smart_pass_v2': 'Passe entre dois ou mais jogadores',
                'playerStats_successful_dribble_leading_to_shot': 'Chute após drible',
                'playerStats_aerial_duel_in_own_penalty_area_success': 'Duelo aéreo na própria área ganho',
                'playerStats_ball_delivery_to_penalty_area': 'Passe para a área do pênalti',
                'playerStats_ball_loss': 'Perda de bola',
                'playerStats_clearance': 'Rebatida',
                'playerStats_cross_success': 'Cruzamento certo',
                'playerStats_cross_to_penalty_area_success': 'Cruzamento para a área do pênalti',
                'playerStats_defensive_duel_regain_success': 'Duelo retomado',
                'playerStats_direct_free_kick_success': 'Falta direta',
                'playerStats_dribble_against_with_take_on_success': 'Drible tomado com ultrapassagem',
                'playerStats_foul_suffered_success': 'Falta sofrida',
                'playerStats_head_goal': 'Gol de cabeça',
                'playerStats_key_pass': 'Passe chave',
                'playerStats_left_throw_in_success': 'Lateral pela esquerda',
                'playerStats_legacy_won_offensive_duel_success': 'playerStats_legacy_dribble_success_success',
                'playerStats_off_the_ball': 'Movimentos sem bola',
                'playerStats_pass_followed_by_teammate_loss_success': 'playerStats_pass_followed_by_teammate_loss_success',
                'playerStats_pass_success': 'Passe certo',
                'playerStats_pass_to_penalty_area': 'Passe para a área do pênalti',
                'playerStats_pass_to_penalty_area_success': 'Passe para a área do pênalti',
                'playerStats_pre_pre_assist': 'Pré pré-assistência',
                'playerStats_pressed_sequence_loss_success': 'playerStats_pressed_sequence_loss_success',
                'playerStats_pressed_sequence_recovery': 'Recuperação pós perda em sequencia',
                'playerStats_received_cross': 'Cruzamento recebido',
                'playerStats_right_throw_in_success': 'Lateral pela direita',
                'playerStats_shot_after_throw_in_success': 'Finalização após lateral',
                'playerStats_shot_buildup_pass_success': 'Passe para saída de bola',
                'playerStats_shot_from_box': 'Finalização dentro da área',
                'playerStats_shot_in_counterattack': 'Finalização em contra-ataque',
                'playerStats_successful_dribble_leading_to_shot_success': 'Finalização após drible',
                'playerStats_touch_in_final_third_success': 'Toque na área',
                'xG/chute': 'xG/chute',
                'playerStats_cross': 'Cruzamento',
                'playerStats_defensive_duel': 'Duelo defensivo',
                'playerStats_dribble': 'Drible',
                'playerStats_dribble_against_success': 'Drible tomado',
                'playerStats_dribble_attempt': 'Tentativa de drible',
                'playerStats_duel_with_foul': 'Duelo com falta',
                'playerStats_duel_with_foul_success': 'Duelo com falta',
                'playerStats_free_kick': 'Falta cobrada',
                'playerStats_goal_from_outside_area_success': 'Gol fora da área',
                'playerStats_ground_duel_success': 'Duelo por baixo',
                'playerStats_head_pass': 'Passe de cabeça',
                'playerStats_highlight': 'playerStats_highlight',
                'playerStats_pass_into_duel': 'Passe em duelo',
                'playerStats_pass_to_zone_fourteen_success': 'Passe para a zona 14',
                'playerStats_pre_assist_success': 'Pré assistência',
                'playerStats_progressive_pass': 'Passe progressivo',
                'playerStats_received_cross_success': 'Cruzamento recebido',
                'playerStats_received_pass': 'Passe recebido',
                'playerStats_recovery_counterpressing_success': 'Pressão pós perda',
                'playerStats_run_success': 'Corrida',
                'playerStats_run_to_final_third': 'Corrida para o terço final',
                'playerStats_short_back_shot_assist_success': 'Passe curto para trás',
                'playerStats_shot_after_free_kick': 'Finalização após cobrança de falta',
                'playerStats_shot_to_near_corner_success': 'playerStats_shot_to_near_corner_success',
                'playerStats_stopped_progress_defensive_duel': 'Duelo que impediu a progressão',
                'playerStats_throw_in_success': 'Lateral',
                'xG/shot': 'xG/shot',
                'playerStats_assist_success': 'Assistência',
                'playerStats_cutback_success': 'playerStats_cutback_success',
                'playerStats_defensive_duel_regain': 'Duelo retomado',
                'playerStats_diagonal_to_flank': 'Passe diagonal para o corredor',
                'playerStats_dribble_against': 'Drible tomado',
                'playerStats_dribble_won_v2_success': 'playerStats_dribble_won_v2',
                'playerStats_duel_success': 'Desarmes',
                'playerStats_free_kick_cross_success': 'Cruzamento em falta',
                'playerStats_free_kick_success': 'Falta cobrada',
                'playerStats_free_kick_with_shot': 'Finalização em falta direta',
                'playerStats_goal': 'Gol',
                'playerStats_goal_after_corner_success': 'Gol após escanteio',
                'playerStats_goal_success': 'Gol',
                'playerStats_kick_off_success': 'Tiro de meta',
                'playerStats_left_foot_goal_success': 'Gol com a perna esquerda',
                'playerStats_one_on_one_success': '1 vs 1',
                'playerStats_penalty_suffered_success': 'Pênalti sofrido',
                'playerStats_run_to_final_third_success': 'Corrida para o terço final',
                'playerStats_shot_after_throw_in': 'Finalização após lateral',
                'playerStats_shot_from_danger_zone': 'Finalização de área perigosa',
                'playerStats_shot_from_penalty_area': 'Finalização na área do pênalti',
                'playerStats_shot_on_goal': 'Finalização no alvo',
                'playerStats_smart_pass_success': 'Passe entre dois ou mais jogadores',
                'playerStats_tackle': 'Carrinho',
                'playerStats_corner_won_from_shot_success': 'Escanteio ganho com chute',
                'playerStats_cross_blocked': 'Cruzamento bloqueado',
                'playerStats_cross_low': 'Cruzamento rasteiro',
                'playerStats_cross_to_goalie_box_success': 'Cruamento para o gol',
                'playerStats_dangerous_own_half_loss_success': 'Bola perdida perigosa em seu campo',
                'playerStats_decisive_goal': 'Gol decisivo',
                'playerStats_deep_completed_run_success': 'Corrida do fundo',
                'playerStats_dribble_in_danger_zone_success': 'Drible em zona perigosa',
                'playerStats_goal_from_cross': 'Gol de cruzamento',
                'playerStats_left_foot_goal': 'Gol com a perna esquerda',
                'playerStats_left_foot_shot_success': 'Finalização com a esquerda',
                'playerStats_loss_success': 'Perda de bola',
                'playerStats_penalty_goal_success': 'Gol de pênalti',
                'playerStats_pre_pre_assist_success': 'Pré pré-assistência',
                'playerStats_received_dangerous_pass_success': 'Passe perigoso recebido',
                'playerStats_regular_foul': 'Falta normal',
                'playerStats_shot_from_danger_zone_success': 'Finalização de zona perigosa',
                'playerStats_shot_from_outside_area_success': 'Finalização de fora da área',
                'playerStats_shot_success': 'Finalização',
                'playerStats_through_pass_v2': 'Passe infiltrado',
                'playerStats_touch_in_final_third': 'Toques no terço final',
                'playerStats_back_pass_success': 'Passe para trás',
                'playerStats_corner_won_from_loose_ball_duel': 'Escanteio ganho em duelo',
                'playerStats_cross_from_right': 'Cruzamento pela direita',
                'playerStats_cross_to_goalie_box': 'Cruzamento para o gol',
                'playerStats_defensive_positioning': 'Posição defensiva correta',
                'playerStats_dribble_success': 'Drible',
                'playerStats_dribble_with_space': 'Drible com espaço',
                'playerStats_dribble_with_take_on': 'Drible com ultrapassagem',
                'playerStats_interception_success': 'Interceptação',
                'playerStats_late_card_foul': 'Cartão tomado',
                'playerStats_loss_after_pass_success': 'Perda de bola após passe',
                'playerStats_low_through_ball': 'Passe infiltrado por baixo',
                'playerStats_opportunity_success': 'Oportunidade de gol',
                'playerStats_pressed_sequence_recovery_success': 'Recuperação pós perda em sequencia',
                'playerStats_received_long_pass_success': 'Passe longo recebido',
                'playerStats_received_pass_in_final_third_on_side': 'playerStats_received_pass_in_final_third_on_side',
                'playerStats_right_foot_goal': 'Gol com a direita',
                'playerStats_shot_after_corner_success': 'Finalização após escanteio',
                'playerStats_shot_block': 'Finalização bloqueada',
                'playerStats_shot_from_play_success': 'Finalização em jogada trabalhada',
                'playerStats_shot_to_far_corner': 'Finalização pra muito pra fora',
                'playerStats_through_pass': 'Passe infiltrado',
                'playerStats_throw_in': 'Lateral',
                'playerStats_action_in_counterattack_success': 'Ações em contra-ataques',
                'playerStats_ball_delivery_to_danger_zone': 'Passe para zona perigosa',
                'playerStats_acceleration_success': 'Aceleração',
                'playerStats_aerial_duel_in_own_penalty_area': 'Duelo aéreo na própria área',
                'playerStats_dribble_in_danger_zone': 'Drible em zona perigosa',
                'playerStats_duel': 'Duelos',
                'playerStats_foul': 'Falta',
                'playerStats_goal_after_free_kick_success': 'Gol após falta',
                'playerStats_head_pass_success': 'Passe de cabeça',
                'playerStats_highlight_success': 'playerStats_highlight_success',
                'playerStats_last_success': 'playerStats_last_success',
                'playerStats_left_foot_shot': 'Finalização com a esquerda',
                'playerStats_legacy_won_offensive_duel': 'playerStats_legacy_won_offensive_duel',
                'playerStats_long_ground_pass': 'Passe longo por baixo',
                'playerStats_missed_ball': 'Bola perdida',
                'playerStats_offensive_duel_success': 'Duelo ofensivo',
                'playerStats_pass_to_final_third': 'Passe para o terço final',
                'playerStats_penalty_goal': 'Gol de pênalti',
                'playerStats_plus_success': 'playerStats_plus_success',
                'playerStats_postmatch_penalty': 'Gol em disputa de pênalti',
                'playerStats_postmatch_penalty_success': 'Gol em disputa de pênalti',
                'playerStats_short_back_shot_assist': 'Passe curto para trás assistência',
                'playerStats_through_pass_v2_success': 'Passe infiltrado',
                'playerStats_xg_shot': 'xG',
                'playerStats_aerial_duel_success': 'Duelo aéreo',
                'playerStats_back_pass': 'Passe para trás',
                'playerStats_ball_entry_in_final_third_success': 'Condução de bola para o terço final',
                'playerStats_buildup_pass_success': 'Passe para saída de bola',
                'playerStats_corner_won_from_another_corner': 'Escanteio ganho de outro escanteio',
                'playerStats_cross_high': 'Cruzamento alto',
                'playerStats_goal_after_corner': 'Gol após escanteio',
                'playerStats_head_shot': 'Finalização de cabeça',
                'playerStats_infraction': 'Infração',
                'playerStats_legacy_dribble_success': 'playerStats_highlight',
                'playerStats_long_pass_into_duel_success': 'Passe longo em duelo',
                'playerStats_long_pass_success': 'Passe longo',
                'playerStats_loss': 'Perda de bola',
                'playerStats_low_through_ball_success': 'Passe infiltrado por baixo',
                'playerStats_non_penalty_goal': 'Gol sem ser de pênalti',
                'playerStats_one_on_one': '1 vs 1',
                'playerStats_pass_followed_by_teammate_loss': 'playerStats_pass_followed_by_teammate_loss',
                'playerStats_received_pass_success': 'Passe certo recebido',
                'playerStats_recovery': 'Recuperação de bola',
                'playerStats_recovery_counterpressing': 'Pressão pós perda',
                'playerStats_run': 'Corrida',
                'playerStats_shot_wide': 'Finalização pra fora',
                'playerStats_total_actions': 'Ações totais',
                'playerStats_touch_in_box_success': 'Toque certo na área',
                'xA diferença': 'xA diferença',
                'xA/assistência': 'xA/assistência',
                'playerStats_assist_from_set_piece': 'Assistência de bola parada',
                'playerStats_blocked_shot': 'Finalização bloqueada',
                'playerStats_cross_from_left_success': 'Cruzamento pela esquerda',
                'playerStats_cross_from_right_success': 'Cruzamento com a direita',
                'playerStats_deep_completed_pass_success': 'Passe profundo',
                'playerStats_deep_completed_run': 'Corrida do fundo',
                'playerStats_defensive_duel_success': 'Duelo defensivo ganho',
                'playerStats_defensive_one_on_one_success': 'Duelo defensivo 1 vs 1',
                'playerStats_diagonal_to_flank_success': 'Passe diagonal para o corredor',
                'playerStats_goal_after_free_kick': 'Gol após falta',
                'playerStats_indirect_free_kick': 'Falta indireta',
                'playerStats_inside_run': 'Corrida por dentro',
                'playerStats_key_pass_success': 'Passe chave',
                'playerStats_lateral_pass_success': 'Passe lateral',
                'playerStats_launch': 'playerStats_launch',
                'playerStats_legacy_dribble_success_success': 'playerStats_legacy_dribble_success_success',
                'playerStats_legacy_won_defensive_duel_success': 'playerStats_legacy_won_defensive_duel_success',
                'playerStats_linkup_play': 'Pivot',
                'playerStats_loose_ball_duel': 'Perda de bola em duelo',
                'playerStats_loss_v2': 'playerStats_loss_v2',
                'playerStats_offensive_duel': 'Duelo ofensivo',
                'playerStats_offensive_shielding_success': 'Proteção da bola (pivot)',
                'playerStats_pass': 'Passe',
                'playerStats_received_pass_in_final_third': 'Passe recebido no terço final',
                'playerStats_received_pass_in_final_third_success': 'Passe recebido no terço final',
                'playerStats_red_card_minute': 'Minuto do cartão vermelho',
                'playerStats_shot_assist_in_counterattack': 'Assistência para finalização em contra-ataque',
                'playerStats_shot_assist_in_counterattack_success': 'Assistência em contra-ataque',
                'playerStats_shot_block_success': 'Finalização bloqueada',
                'playerStats_shot_from_cross_success': 'Finalização em cruzamentos',
                'playerStats_any_free_kick': 'Falta cobrada',
                'playerStats_back_pass_to_gk': 'Passe curto pro goleiro',
                'playerStats_dangerous_opponent_half_recovery_success': 'Recuperação de bola perigosa no campo adversário',
                'playerStats_dribble_with_space_success': 'Drible com espaço',
                'playerStats_dribbled_past_attempt_success': 'Tentativa de drible contra',
                'playerStats_forward_pass_success': 'Passe para frente',
                'playerStats_free_kick_cross': 'Falta cruzada',
                'playerStats_free_kick_with_shot_success': 'Falta direta com finalização',
                'playerStats_hand_foul': 'Mão na bola',
                'playerStats_head_shot_success': 'Finalização de cabeça',
                'playerStats_kick_off': 'Tiro de meta',
                'playerStats_last': 'playerStats_last',
                'playerStats_lateral_pass': 'Passe lateral',
                'playerStats_legacy_won_defensive_duel': 'playerStats_legacy_won_defensive_duel',
                'playerStats_loss_after_duel': 'Perda de bola após duelo',
                'playerStats_loss_v2_success': 'playerStats_loss_v2_success',
                'playerStats_out_of_play_foul': 'Falta fora da disputa de bola',
                'playerStats_pending_card': 'Pendurado',
                'playerStats_pre_assist': 'Pré assistência',
                'playerStats_pressed_sequence_loss': 'Perda de bola após pressão',
                'playerStats_right_foot_goal_success': 'Gols com a direita',
                'playerStats_right_foot_shot': 'Finalização certa com a perna direita',
                'playerStats_short_medium_pass': 'Passe curto/médio',
                'playerStats_shot_from_outside_area': 'Finalização de fora da área',
                'playerStats_shot_from_play': 'Finalização em jogadas trabalhadas',
                'playerStats_shot_on_goal_assist': 'Assistência para chute no alvo',
                'playerStats_shot_on_post': 'Finalização na trave',
                'playerStats_touch_in_box': 'Toque na área',
                'playerStats_yellow_card_minute': 'Minuto do cartão amarelo',
                'playerStats_cross_from_left': 'Cruzamento pela esquerda',
                'playerStats_any_free_kick_success': 'Falta cobrada',
                'playerStats_ball_delivery_to_penalty_area_success': 'Passe para a área do pênalti',
                'playerStats_dangerous_lost_defensive_duel': 'Duelo defensivo perigoso perdido',
                'playerStats_deep_completed_cross_success': 'Cruzamento do fundo',
                'playerStats_foul_suffered': 'Falta sofrida',
                'playerStats_free_kick_shot_gained': 'playerStats_free_kick_shot_gained',
                'playerStats_goal_after_throw_in': 'Gol após lateral',
                'playerStats_goal_after_throw_in_success': 'Gol após lateral',
                'playerStats_goal_from_outside_area': 'Gols de fora da área',
                'playerStats_interception': 'Interceptação',
                'playerStats_launch_success': 'playerStats_launch_success',
                'playerStats_legacy_won_duel_success': 'playerStats_dribble_won_v2',
                'playerStats_opportunity': 'Oportunidade de gol',
                'playerStats_own_half_loss': 'Perda de bola no próprio campo',
                'playerStats_pass_behind_the_back': 'Passe por trás das costas',
                'playerStats_received_pass_in_final_third_on_side_success': 'playerStats_received_pass_in_final_third_on_side_success',
                'playerStats_right_foot_shot_success': 'Finalização com a direita',
                'playerStats_shot_from_penalty_area_success': 'Finalização na área do pênalti',
                'playerStats_touch': 'Toque',
                'playerStats_xg_assist': 'xA',
                'playerStats_action_in_counterattack': 'Ações em contra-ataque',
                'playerStats_defensive_one_on_one': 'Duelo defensivo 1 vs 1',
                'playerStats_dribble_with_progress_success': 'Drible com progresão',
                'playerStats_dribble_with_take_on_success': 'Drible com ultrapassagem',
                'playerStats_first_goal': 'Primeiro gol',
                'playerStats_head_goal_success': 'Gol de cabeça',
                'playerStats_left_throw_in': 'Lateral pela esquerda',
                'playerStats_linkup_play_success': 'Pivot',
                'playerStats_loss_after_duel_success': 'Perda de bola após duelo',
                'playerStats_loss_after_pass': 'Perda de bola após passe',
                'playerStats_meaningless': 'playerStats_meaningless',
                'playerStats_non_penalty_goal_success': 'Gol sem ser de pênalti',
                'playerStats_pass_behind_the_back_success': 'Passe por trás da costas',
                'playerStats_pass_to_another_flank': 'Virada de jogo',
                'playerStats_pass_to_penalty_area_v2_success': 'Passe para a área do pênalti',
                'playerStats_progressive_run': 'Corrida progressiva',
                'playerStats_quick_recovery': 'Recuperação pós perda',
                'playerStats_received_long_pass': 'Passe longo recebido',
                'playerStats_shot_assist': 'Assistência para finalização',
                'playerStats_shot_assist_success': 'Assistência',
                'playerStats_shot_buildup_pass': 'Finalização em jogada bem trabalhada',
                'playerStats_shot_in_counterattack_success': 'Finalização em contra-ataque',
                'playerStats_stopped_progress_defensive_duel_success': 'Duelo defensivo impedindo progressão',
                'playerStats_total_actions_success': 'Ações totais certas',
                'playerStats_under_pressure': 'Pressionado',
                'xG diference': 'xG diference',
                'playerStats_ball_entry_in_final_third': 'Condução de bola para o terço final',
                'playerStats_corner_success': 'Escanteio',
                'playerStats_counterattack_interception': 'Interceptação em contra-ataque',
                'playerStats_deep_completed_pass': 'Passe profundo',
                'playerStats_free_kick_shot_success': 'Falta direta com finalização',
                'playerStats_goal_from_cross_success': 'Gol de cruzamento',
                'playerStats_heading_success': 'Cabeceio',
                'playerStats_long_pass_or_cross_success': 'Passe longo ou cruzamento',
                'playerStats_opponent_half_recovery_success': 'Recuperação no campo adversário',
                'playerStats_opportunity_creation': 'Oportunidade criada',
                'playerStats_pass_into_duel_success': 'Passe em duelo',
                'playerStats_penalty_success': 'Pênalti',
                'playerStats_progressive_pass_success': 'Passe progressivo',
                'playerStats_progressive_run_success': 'Corrida progressiva',
                'playerStats_quick_recovery_success': 'Recuperação pós perda',
                'playerStats_received_progressive_pass': 'Passe progressivo recebido',
                'playerStats_received_progressive_pass_success': 'Passe progressivo recebido',
                'playerStats_recovery_success': 'Recuperação de bola',
                'playerStats_red_cards': 'Cartão vermelho',
                'playerStats_shot_to_far_corner_success': 'playerStats_shot_to_far_corner_success',
                'playerStats_shot_to_near_corner': 'playerStats_shot_to_near_corner',
                'playerStats_smart_pass': 'Passe entre dois ou mais jogadores',
                'playerStats_tackle_success': 'Carrinho bem sucedido',
                'playerStats_through_pass_success': 'Passe infiltrado',
                'playerStats_under_pressure_success': 'Pressionado',
                'playerStats_defensive_mistake': 'Erro defensivo',
                'playerStats_aerial_duel': 'Duélo aéreo',
                'Passes Certos %': 'Passes Certos %',
                'playerStats_corner_with_shot': 'Escanteio com finalização',
                'playerStats_corner_with_shot_success': 'Escanteios com finalização',
                'playerStats_corner_won_from_off_duel': 'Escanteio ganho em duelo',
                'playerStats_cross_block': 'Cruzamento bloqueado',
                'playerStats_cross_high_success': 'Cruzamento alto',
                'playerStats_cutback': 'playerStats_cutback',
                'playerStats_dangerous_own_half_loss': 'Bola perdida perigosa em seu campo',
                'playerStats_decisive_goal_success': 'Gol decisivo',
                'playerStats_deep_completed_cross': 'Cruzamento do fundo',
                'playerStats_dribble_attempt_success': 'Tentativa de drible',
                'playerStats_dribbled_past_attempt': 'Tentativa de drible contra',
                'playerStats_first_goal_success': 'Primeiro gol',
                'playerStats_forward_pass': 'Passe para frente',
                'playerStats_indirect_free_kick_success': 'Falta indireta',
                'playerStats_long_pass_into_duel': 'Passe longo em duelo',
                'playerStats_pass_to_final_third_success': 'Passe para o terço final',
                'playerStats_pass_within_final_third': 'Passe  no terço final',
                'playerStats_pass_within_final_third_success': 'Passe  no terço final',
                'playerStats_penalty': 'Penalti',
                'playerStats_penalty_suffered': 'Pênalti sofrido',
                'playerStats_pre_shot_assist': 'Pré-assistência para finalização',
                'playerStats_real_won_duel_success': 'playerStats_dribble_won_v2',
                'playerStats_short_medium_pass_success': 'playerStats_short_medium_pass_success',
                'playerStats_shot_after_corner': 'Finalização em escanteios',
                'playerStats_touch_in_penalty_area_success': 'Toque certo na área do pênalti',
                'xA/assist': 'xA/assist',
                'xG diferença': 'xG diferença',
                'playerStats_acceleration': 'Aceleração',
                'playerStats_action_success': 'Ações',
                'playerStats_any_goal_success': 'Gol',
                'playerStats_buildup_pass': 'Passe para saída de bola',
                'playerStats_card_suffered_success': 'Cartão tomado',
                'playerStats_clearance_success': 'Rebatida',
                'playerStats_corner_won_from_off_duel_success': 'Escanteio ganho em duelo',
                'playerStats_corner_won_from_shot': 'Escanteio ganho com chute',
                'playerStats_cross_low_success': 'Cruzamento por baixo',
                'playerStats_dangerous_foul': 'Falta perigosa',
                'playerStats_key_pass_v2_success': 'Passe chave',
                'playerStats_long_ground_pass_success': 'Passe longo por baixo',
                'playerStats_long_pass': 'Passe longo',
                'playerStats_minus': 'playerStats_minus',
                'playerStats_misconduct': 'Indisciplina',
                'playerStats_offensive_duel_with_progress_success': 'Duelo ofensivo com progressão bem sucedido',
                'playerStats_offensive_shielding': 'Proteção da bola (pivot)',
                'playerStats_own_half_loss_success': 'Perda de bola no próprio campo',
                'playerStats_pick_up': 'playerStats_pick_up',
                'playerStats_pre_shot_assist_success': 'Pré-assistência para finalização',
                'playerStats_protest_foul': 'Reclamação',
                'playerStats_shot': 'Finalização',
                'playerStats_shot_after_free_kick_success': 'Finalização após cobrança de falta',
                'playerStats_smart_pass_v2_success': 'Passe entre dois ou mais jogadores',
                'playerStats_yellow_cards': 'Cartão amarelo'
         }
        return dic_translate

translate = Translate()
